// 300 domande di cultura generale italiana, difficoltà medio-alta.
// Formato: { q: testo, o: [4 opzioni], c: indice (0-3) della risposta corretta }.
// La risposta corretta (c) resta SOLO sul server: ai partecipanti viene inviata
// solo dopo la chiusura della domanda.

export const QUESTIONS = [
  // ---- Storia ----
  { q: "In che anno è stata proclamata l'Unità d'Italia?", o: ["1861", "1848", "1871", "1815"], c: 0 },
  { q: "Chi fu il primo re d'Italia?", o: ["Vittorio Emanuele II", "Umberto I", "Vittorio Emanuele III", "Carlo Alberto"], c: 0 },
  { q: "In che anno cadde l'Impero Romano d'Occidente?", o: ["476 d.C.", "410 d.C.", "395 d.C.", "527 d.C."], c: 0 },
  { q: "Chi guidò la spedizione dei Mille?", o: ["Giuseppe Garibaldi", "Camillo Cavour", "Giuseppe Mazzini", "Vittorio Emanuele II"], c: 0 },
  { q: "In che anno iniziò la Prima guerra mondiale?", o: ["1914", "1915", "1912", "1918"], c: 0 },
  { q: "In che anno l'Italia entrò nella Prima guerra mondiale?", o: ["1915", "1914", "1916", "1917"], c: 0 },
  { q: "In che anno finì la Seconda guerra mondiale in Europa?", o: ["1945", "1944", "1946", "1943"], c: 0 },
  { q: "Chi era il capo del fascismo italiano?", o: ["Benito Mussolini", "Italo Balbo", "Galeazzo Ciano", "Dino Grandi"], c: 0 },
  { q: "In che anno fu proclamata la Repubblica Italiana?", o: ["1946", "1948", "1945", "1947"], c: 0 },
  { q: "Quando entrò in vigore la Costituzione italiana?", o: ["1° gennaio 1948", "2 giugno 1946", "1° gennaio 1950", "25 aprile 1945"], c: 0 },
  { q: "Chi scoprì l'America nel 1492?", o: ["Cristoforo Colombo", "Amerigo Vespucci", "Marco Polo", "Ferdinando Magellano"], c: 0 },
  { q: "Chi fu il primo imperatore romano?", o: ["Augusto", "Giulio Cesare", "Nerone", "Traiano"], c: 0 },
  { q: "In che anno iniziò la Rivoluzione francese?", o: ["1789", "1799", "1776", "1815"], c: 0 },
  { q: "Chi fu Napoleone Bonaparte?", o: ["Imperatore dei Francesi", "Re d'Inghilterra", "Zar di Russia", "Re di Spagna"], c: 0 },
  { q: "In che anno avvenne la presa della Bastiglia?", o: ["1789", "1790", "1788", "1799"], c: 0 },
  { q: "In quale città fu firmato il trattato che istituì la CEE nel 1957?", o: ["Roma", "Parigi", "Bruxelles", "Maastricht"], c: 0 },
  { q: "In che anno cadde il Muro di Berlino?", o: ["1989", "1991", "1987", "1990"], c: 0 },
  { q: "Su quale città fu sganciata la prima bomba atomica nel 1945?", o: ["Hiroshima", "Nagasaki", "Tokyo", "Osaka"], c: 0 },
  { q: "Quale civiltà costruì le piramidi di Giza?", o: ["Egizi", "Maya", "Romani", "Greci"], c: 0 },
  { q: "Chi era Giulio Cesare?", o: ["Generale e politico romano", "Imperatore greco", "Re etrusco", "Faraone egizio"], c: 0 },
  { q: "Di chi segnò la sconfitta la battaglia di Waterloo (1815)?", o: ["Napoleone", "Wellington", "Nelson", "Bismarck"], c: 0 },
  { q: "In che anno l'uomo sbarcò sulla Luna?", o: ["1969", "1965", "1972", "1961"], c: 0 },
  { q: "Chi fu il primo uomo nello spazio?", o: ["Jurij Gagarin", "Neil Armstrong", "John Glenn", "Aleksej Leonov"], c: 0 },
  { q: "In quale paese ebbe origine il Rinascimento?", o: ["Italia", "Francia", "Inghilterra", "Spagna"], c: 0 },
  { q: "Quale famiglia dominò Firenze nel Rinascimento?", o: ["Medici", "Borgia", "Sforza", "Visconti"], c: 0 },
  { q: "In quale anno fu fondata Roma secondo la tradizione?", o: ["753 a.C.", "509 a.C.", "27 a.C.", "476 d.C."], c: 0 },
  { q: "Chi guidò la marcia su Roma del 1922?", o: ["Mussolini", "Garibaldi", "D'Annunzio", "Vittorio Emanuele III"], c: 0 },
  { q: "In quale paese fu firmata la Magna Charta (1215)?", o: ["Inghilterra", "Francia", "Italia", "Germania"], c: 0 },
  { q: "Chi era Marco Polo?", o: ["Mercante ed esploratore veneziano", "Pittore fiorentino", "Condottiero romano", "Papa medievale"], c: 0 },
  { q: "La Guerra Fredda contrappose gli USA a quale potenza?", o: ["Unione Sovietica", "Cina", "Germania", "Giappone"], c: 0 },
  { q: "Chi fu l'ultimo re d'Italia?", o: ["Umberto II", "Vittorio Emanuele III", "Vittorio Emanuele II", "Umberto I"], c: 0 },
  { q: "Quale trattato pose ufficialmente fine alla Prima guerra mondiale?", o: ["Trattato di Versailles", "Trattato di Roma", "Pace di Westfalia", "Congresso di Vienna"], c: 0 },
  { q: "Chi era Cleopatra?", o: ["Regina d'Egitto", "Imperatrice romana", "Regina di Grecia", "Regina di Persia"], c: 0 },
  { q: "In che anno avvenne lo sbarco in Normandia (D-Day)?", o: ["1944", "1945", "1943", "1942"], c: 0 },
  { q: "Quale antica città fu sepolta dall'eruzione del Vesuvio nel 79 d.C.?", o: ["Pompei", "Ostia", "Cuma", "Paestum"], c: 0 },
  { q: "Chi era Carlo Magno?", o: ["Re dei Franchi e imperatore", "Re d'Inghilterra", "Imperatore bizantino", "Papa di Roma"], c: 0 },
  { q: "Contro chi combatté principalmente la Resistenza italiana?", o: ["Nazifascismo", "Monarchia sabauda", "Impero austriaco", "Chiesa cattolica"], c: 0 },
  { q: "Quale popolo fu guidato da Annibale contro Roma?", o: ["Cartaginesi", "Galli", "Greci", "Egizi"], c: 0 },
  { q: "Chi pronunciò la celebre frase 'Il dado è tratto'?", o: ["Giulio Cesare", "Augusto", "Nerone", "Cicerone"], c: 0 },
  { q: "Quale regina inglese regnò nel periodo elisabettiano (XVI secolo)?", o: ["Elisabetta I", "Vittoria", "Maria Stuarda", "Anna"], c: 0 },

  // ---- Geografia ----
  { q: "Qual è la capitale d'Italia?", o: ["Roma", "Milano", "Napoli", "Torino"], c: 0 },
  { q: "Qual è il fiume più lungo d'Italia?", o: ["Po", "Tevere", "Adige", "Arno"], c: 0 },
  { q: "Qual è la montagna più alta d'Italia?", o: ["Monte Bianco", "Monte Rosa", "Cervino", "Gran Paradiso"], c: 0 },
  { q: "Qual è l'isola più grande d'Italia?", o: ["Sicilia", "Sardegna", "Elba", "Ischia"], c: 0 },
  { q: "Qual è il lago più grande d'Italia per superficie?", o: ["Lago di Garda", "Lago Maggiore", "Lago di Como", "Trasimeno"], c: 0 },
  { q: "Quante regioni ha l'Italia?", o: ["20", "19", "21", "18"], c: 0 },
  { q: "Qual è la capitale della Francia?", o: ["Parigi", "Lione", "Marsiglia", "Nizza"], c: 0 },
  { q: "Qual è la capitale della Spagna?", o: ["Madrid", "Barcellona", "Siviglia", "Valencia"], c: 0 },
  { q: "Qual è il vulcano attivo più alto d'Europa?", o: ["Etna", "Vesuvio", "Stromboli", "Teide"], c: 0 },
  { q: "In quale regione si trova Venezia?", o: ["Veneto", "Lombardia", "Friuli-Venezia Giulia", "Emilia-Romagna"], c: 0 },
  { q: "Qual è il mare a est dell'Italia?", o: ["Mar Adriatico", "Mar Tirreno", "Mar Ionio", "Mar Ligure"], c: 0 },
  { q: "Qual è lo stato più piccolo del mondo?", o: ["Città del Vaticano", "Monaco", "San Marino", "Liechtenstein"], c: 0 },
  { q: "Quale fiume attraversa Roma?", o: ["Tevere", "Po", "Arno", "Adige"], c: 0 },
  { q: "In quale regione si trova Napoli?", o: ["Campania", "Lazio", "Puglia", "Calabria"], c: 0 },
  { q: "Qual è la capitale della Germania?", o: ["Berlino", "Monaco", "Francoforte", "Amburgo"], c: 0 },
  { q: "Qual è il continente più grande?", o: ["Asia", "Africa", "America", "Europa"], c: 0 },
  { q: "Qual è l'oceano più grande?", o: ["Pacifico", "Atlantico", "Indiano", "Artico"], c: 0 },
  { q: "Qual è il deserto caldo più grande del mondo?", o: ["Sahara", "Gobi", "Kalahari", "Atacama"], c: 0 },
  { q: "In quale regione si trova il Colosseo?", o: ["Lazio", "Toscana", "Campania", "Umbria"], c: 0 },
  { q: "Qual è la capitale del Regno Unito?", o: ["Londra", "Manchester", "Edimburgo", "Liverpool"], c: 0 },
  { q: "Quale stretto separa la Sicilia dalla Calabria?", o: ["Stretto di Messina", "Stretto di Gibilterra", "Bosforo", "Canale d'Otranto"], c: 0 },
  { q: "Qual è la capitale della Russia?", o: ["Mosca", "San Pietroburgo", "Kiev", "Minsk"], c: 0 },
  { q: "Quale catena montuosa percorre l'Italia da nord a sud?", o: ["Appennini", "Alpi", "Pirenei", "Carpazi"], c: 0 },
  { q: "Qual è la capitale del Giappone?", o: ["Tokyo", "Osaka", "Kyoto", "Nagoya"], c: 0 },
  { q: "In quale regione si trova la Valle dei Templi (Agrigento)?", o: ["Sicilia", "Sardegna", "Calabria", "Puglia"], c: 0 },
  { q: "Qual è la capitale degli Stati Uniti?", o: ["Washington", "New York", "Los Angeles", "Chicago"], c: 0 },
  { q: "Qual è il capoluogo della Toscana?", o: ["Firenze", "Pisa", "Siena", "Livorno"], c: 0 },
  { q: "Qual è il capoluogo della Lombardia?", o: ["Milano", "Bergamo", "Brescia", "Como"], c: 0 },
  { q: "Qual è il capoluogo del Piemonte?", o: ["Torino", "Novara", "Asti", "Cuneo"], c: 0 },
  { q: "Qual è il capoluogo della Sicilia?", o: ["Palermo", "Catania", "Messina", "Siracusa"], c: 0 },
  { q: "Qual è il capoluogo della Puglia?", o: ["Bari", "Lecce", "Taranto", "Foggia"], c: 0 },
  { q: "Qual è la capitale della Grecia?", o: ["Atene", "Salonicco", "Sparta", "Patrasso"], c: 0 },
  { q: "Qual è la capitale del Portogallo?", o: ["Lisbona", "Porto", "Coimbra", "Faro"], c: 0 },
  { q: "Quale isola italiana è famosa per i nuraghi?", o: ["Sardegna", "Sicilia", "Elba", "Capri"], c: 0 },
  { q: "Qual è la capitale dell'Egitto?", o: ["Il Cairo", "Alessandria", "Luxor", "Giza"], c: 0 },
  { q: "Quale catena montuosa separa Europa e Asia?", o: ["Monti Urali", "Alpi", "Carpazi", "Pirenei"], c: 0 },
  { q: "Qual è la capitale dei Paesi Bassi (Olanda)?", o: ["Amsterdam", "Rotterdam", "L'Aia", "Utrecht"], c: 0 },
  { q: "Quale regione italiana confina con l'Austria e la Slovenia?", o: ["Friuli-Venezia Giulia", "Veneto", "Trentino-Alto Adige", "Lombardia"], c: 0 },
  { q: "Qual è il fiume che attraversa Firenze?", o: ["Arno", "Tevere", "Po", "Adige"], c: 0 },
  { q: "Qual è la capitale della Svizzera?", o: ["Berna", "Zurigo", "Ginevra", "Basilea"], c: 0 },

  // ---- Arte e architettura ----
  { q: "Chi dipinse la Gioconda?", o: ["Leonardo da Vinci", "Michelangelo", "Raffaello", "Caravaggio"], c: 0 },
  { q: "Chi dipinse la volta della Cappella Sistina?", o: ["Michelangelo", "Leonardo da Vinci", "Raffaello", "Botticelli"], c: 0 },
  { q: "Dove è conservata la Gioconda?", o: ["Louvre, Parigi", "Uffizi, Firenze", "Prado, Madrid", "British Museum"], c: 0 },
  { q: "Chi scolpì il David conservato a Firenze?", o: ["Michelangelo", "Donatello", "Bernini", "Canova"], c: 0 },
  { q: "Chi dipinse 'La nascita di Venere'?", o: ["Botticelli", "Tiziano", "Giotto", "Raffaello"], c: 0 },
  { q: "In quale città si trova la Torre pendente?", o: ["Pisa", "Bologna", "Firenze", "Siena"], c: 0 },
  { q: "Chi dipinse 'L'ultima cena' (Cenacolo)?", o: ["Leonardo da Vinci", "Michelangelo", "Raffaello", "Tiziano"], c: 0 },
  { q: "Quale stile è caratterizzato da archi a sesto acuto e guglie slanciate?", o: ["Gotico", "Romanico", "Barocco", "Neoclassico"], c: 0 },
  { q: "Chi progettò la cupola di Santa Maria del Fiore a Firenze?", o: ["Brunelleschi", "Michelangelo", "Bramante", "Alberti"], c: 0 },
  { q: "Chi dipinse 'Guernica'?", o: ["Pablo Picasso", "Salvador Dalí", "Joan Miró", "Henri Matisse"], c: 0 },
  { q: "Di quale corrente artistica fu esponente Salvador Dalí?", o: ["Surrealismo", "Cubismo", "Impressionismo", "Futurismo"], c: 0 },
  { q: "Chi dipinse 'Notte stellata'?", o: ["Vincent van Gogh", "Claude Monet", "Paul Cézanne", "Paul Gauguin"], c: 0 },
  { q: "Quale artista è famoso per le tele tagliate ('Concetto spaziale')?", o: ["Lucio Fontana", "Alberto Burri", "Amedeo Modigliani", "Giorgio de Chirico"], c: 0 },
  { q: "Chi affrescò la Cappella degli Scrovegni a Padova?", o: ["Giotto", "Cimabue", "Duccio", "Masaccio"], c: 0 },
  { q: "In quale museo di Firenze si trova il David di Michelangelo?", o: ["Galleria dell'Accademia", "Uffizi", "Palazzo Pitti", "Bargello"], c: 0 },
  { q: "Chi scolpì 'L'estasi di Santa Teresa'?", o: ["Gian Lorenzo Bernini", "Borromini", "Canova", "Michelangelo"], c: 0 },
  { q: "Quale movimento fu fondato in Italia da Marinetti nel 1909?", o: ["Futurismo", "Cubismo", "Dadaismo", "Surrealismo"], c: 0 },
  { q: "Chi dipinse 'L'urlo'?", o: ["Edvard Munch", "Gustav Klimt", "Egon Schiele", "Vasilij Kandinskij"], c: 0 },
  { q: "Quale pittore impressionista è celebre per le 'Ninfee'?", o: ["Claude Monet", "Édouard Manet", "Edgar Degas", "Auguste Renoir"], c: 0 },
  { q: "Chi dipinse 'Il bacio' (1908), celebre per l'oro?", o: ["Gustav Klimt", "Egon Schiele", "Edvard Munch", "Marc Chagall"], c: 0 },
  { q: "Quale artista italiano è noto per i ritratti dai colli allungati?", o: ["Amedeo Modigliani", "Giorgio Morandi", "Umberto Boccioni", "Carlo Carrà"], c: 0 },
  { q: "In quale paese si trova la Reggia di Versailles?", o: ["Francia", "Italia", "Spagna", "Austria"], c: 0 },
  { q: "Chi disegnò la cupola della basilica di San Pietro a Roma?", o: ["Michelangelo", "Bernini", "Maderno", "Borromini"], c: 0 },
  { q: "Di quale pittore è celebre il forte chiaroscuro e opere come 'Vocazione di San Matteo'?", o: ["Caravaggio", "Tiziano", "Tintoretto", "Veronese"], c: 0 },
  { q: "Chi dipinse 'La ronda di notte'?", o: ["Rembrandt", "Vermeer", "Rubens", "Van Dyck"], c: 0 },
  { q: "In quale città si trova il Museo del Prado?", o: ["Madrid", "Parigi", "San Pietroburgo", "Firenze"], c: 0 },
  { q: "Chi scolpì 'Amore e Psiche' in stile neoclassico?", o: ["Antonio Canova", "Bernini", "Donatello", "Thorvaldsen"], c: 0 },
  { q: "Quale città è famosa per i mosaici bizantini di San Vitale?", o: ["Ravenna", "Venezia", "Palermo", "Roma"], c: 0 },
  { q: "A quale corrente europea corrisponde lo stile Liberty italiano?", o: ["Art Nouveau", "Art Déco", "Bauhaus", "Espressionismo"], c: 0 },
  { q: "Chi dipinse gli affreschi delle Stanze Vaticane, tra cui 'La scuola di Atene'?", o: ["Raffaello", "Michelangelo", "Leonardo", "Perugino"], c: 0 },

  // ---- Letteratura ----
  { q: "Chi scrisse la Divina Commedia?", o: ["Dante Alighieri", "Francesco Petrarca", "Giovanni Boccaccio", "Ludovico Ariosto"], c: 0 },
  { q: "In quante cantiche è divisa la Divina Commedia?", o: ["Tre", "Due", "Quattro", "Cinque"], c: 0 },
  { q: "Chi accompagna Dante nell'Inferno?", o: ["Virgilio", "Beatrice", "Stazio", "Catone"], c: 0 },
  { q: "Chi scrisse 'I Promessi Sposi'?", o: ["Alessandro Manzoni", "Giacomo Leopardi", "Ugo Foscolo", "Italo Svevo"], c: 0 },
  { q: "Chi sono i due protagonisti de 'I Promessi Sposi'?", o: ["Renzo e Lucia", "Paolo e Francesca", "Romeo e Giulietta", "Orlando e Angelica"], c: 0 },
  { q: "Chi scrisse la poesia 'L'Infinito'?", o: ["Giacomo Leopardi", "Alessandro Manzoni", "Ugo Foscolo", "Giosuè Carducci"], c: 0 },
  { q: "Chi è l'autore del 'Decameron'?", o: ["Giovanni Boccaccio", "Francesco Petrarca", "Dante Alighieri", "Niccolò Machiavelli"], c: 0 },
  { q: "Chi scrisse 'Il Principe'?", o: ["Niccolò Machiavelli", "Francesco Guicciardini", "Baldassarre Castiglione", "Giordano Bruno"], c: 0 },
  { q: "Chi scrisse 'Orlando Furioso'?", o: ["Ludovico Ariosto", "Torquato Tasso", "Matteo Maria Boiardo", "Luigi Pulci"], c: 0 },
  { q: "Chi scrisse 'Gerusalemme liberata'?", o: ["Torquato Tasso", "Ludovico Ariosto", "Giambattista Marino", "Alessandro Tassoni"], c: 0 },
  { q: "Chi scrisse 'Le avventure di Pinocchio'?", o: ["Carlo Collodi", "Edmondo De Amicis", "Gianni Rodari", "Emilio Salgari"], c: 0 },
  { q: "Chi scrisse il libro 'Cuore'?", o: ["Edmondo De Amicis", "Carlo Collodi", "Gianni Rodari", "Giovanni Verga"], c: 0 },
  { q: "Quale scrittore siciliano scrisse 'I Malavoglia'?", o: ["Giovanni Verga", "Luigi Pirandello", "Leonardo Sciascia", "Tomasi di Lampedusa"], c: 0 },
  { q: "Chi scrisse 'Il fu Mattia Pascal'?", o: ["Luigi Pirandello", "Italo Svevo", "Gabriele D'Annunzio", "Alberto Moravia"], c: 0 },
  { q: "Quale autore di 'Sei personaggi in cerca d'autore' vinse il Nobel nel 1934?", o: ["Luigi Pirandello", "Salvatore Quasimodo", "Eugenio Montale", "Grazia Deledda"], c: 0 },
  { q: "Chi scrisse 'Il Gattopardo'?", o: ["Giuseppe Tomasi di Lampedusa", "Leonardo Sciascia", "Giovanni Verga", "Luigi Pirandello"], c: 0 },
  { q: "Quale poeta scrisse 'Il sabato del villaggio'?", o: ["Giacomo Leopardi", "Giovanni Pascoli", "Giosuè Carducci", "Ugo Foscolo"], c: 0 },
  { q: "Chi scrisse 'La coscienza di Zeno'?", o: ["Italo Svevo", "Luigi Pirandello", "Alberto Moravia", "Cesare Pavese"], c: 0 },
  { q: "Chi è l'autore di 'Se questo è un uomo'?", o: ["Primo Levi", "Italo Calvino", "Cesare Pavese", "Elio Vittorini"], c: 0 },
  { q: "Chi scrisse 'Il barone rampante'?", o: ["Italo Calvino", "Dino Buzzati", "Cesare Pavese", "Alberto Moravia"], c: 0 },
  { q: "Chi scrisse 'Il nome della rosa'?", o: ["Umberto Eco", "Italo Calvino", "Andrea Camilleri", "Antonio Tabucchi"], c: 0 },
  { q: "Quale scrittore ha creato il commissario Montalbano?", o: ["Andrea Camilleri", "Leonardo Sciascia", "Umberto Eco", "Gianrico Carofiglio"], c: 0 },
  { q: "Chi scrisse la tragedia 'Romeo e Giulietta'?", o: ["William Shakespeare", "Molière", "Goethe", "Christopher Marlowe"], c: 0 },
  { q: "Chi scrisse 'Don Chisciotte della Mancia'?", o: ["Miguel de Cervantes", "Lope de Vega", "Jorge Luis Borges", "Gabriel García Márquez"], c: 0 },
  { q: "Chi scrisse 'I Miserabili'?", o: ["Victor Hugo", "Honoré de Balzac", "Émile Zola", "Gustave Flaubert"], c: 0 },
  { q: "Chi scrisse 'Guerra e pace'?", o: ["Lev Tolstoj", "Fëdor Dostoevskij", "Anton Cechov", "Nikolaj Gogol"], c: 0 },
  { q: "Chi scrisse la tragedia 'Amleto'?", o: ["William Shakespeare", "Christopher Marlowe", "Ben Jonson", "Oscar Wilde"], c: 0 },
  { q: "Durante quale evento è ambientata la cornice del Decameron?", o: ["La peste del 1348", "Una guerra", "Una carestia", "Un terremoto"], c: 0 },
  { q: "Quale poeta italiano vinse il Premio Nobel nel 1975?", o: ["Eugenio Montale", "Salvatore Quasimodo", "Giuseppe Ungaretti", "Umberto Saba"], c: 0 },
  { q: "Chi scrisse 'La locandiera' e riformò il teatro comico italiano?", o: ["Carlo Goldoni", "Vittorio Alfieri", "Pietro Metastasio", "Luigi Pirandello"], c: 0 },

  // ---- Scienza e natura ----
  { q: "Qual è il simbolo chimico dell'oro?", o: ["Au", "Ag", "Or", "Go"], c: 0 },
  { q: "Qual è la formula chimica dell'acqua?", o: ["H₂O", "CO₂", "O₂", "H₂"], c: 0 },
  { q: "Quanti pianeti compongono il Sistema Solare?", o: ["Otto", "Nove", "Sette", "Dieci"], c: 0 },
  { q: "Qual è il pianeta più vicino al Sole?", o: ["Mercurio", "Venere", "Terra", "Marte"], c: 0 },
  { q: "Qual è il pianeta più grande del Sistema Solare?", o: ["Giove", "Saturno", "Nettuno", "Urano"], c: 0 },
  { q: "Qual è la stella più vicina alla Terra?", o: ["Il Sole", "Proxima Centauri", "Sirio", "Polaris"], c: 0 },
  { q: "Chi formulò la teoria della relatività?", o: ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Niels Bohr"], c: 0 },
  { q: "Chi formulò la legge di gravitazione universale?", o: ["Isaac Newton", "Albert Einstein", "Keplero", "Galileo Galilei"], c: 0 },
  { q: "Quante ossa ha mediamente il corpo umano adulto?", o: ["206", "300", "150", "250"], c: 0 },
  { q: "Quale organo pompa il sangue nel corpo?", o: ["Cuore", "Fegato", "Polmoni", "Reni"], c: 0 },
  { q: "Qual è il gas più abbondante nell'atmosfera terrestre?", o: ["Azoto", "Ossigeno", "Anidride carbonica", "Idrogeno"], c: 0 },
  { q: "Qual è il simbolo chimico del ferro?", o: ["Fe", "Fr", "Ir", "F"], c: 0 },
  { q: "Quale scienziato formulò la teoria dell'evoluzione per selezione naturale?", o: ["Charles Darwin", "Gregor Mendel", "Jean-Baptiste Lamarck", "Louis Pasteur"], c: 0 },
  { q: "Qual è l'unità di misura della corrente elettrica?", o: ["Ampere", "Volt", "Watt", "Ohm"], c: 0 },
  { q: "Qual è approssimativamente la velocità della luce nel vuoto?", o: ["300.000 km/s", "30.000 km/s", "3.000 km/s", "3 milioni km/s"], c: 0 },
  { q: "Quale pianeta è noto come il 'Pianeta Rosso'?", o: ["Marte", "Venere", "Giove", "Mercurio"], c: 0 },
  { q: "In quale parte della cellula è contenuto il DNA?", o: ["Nucleo", "Mitocondrio", "Membrana", "Citoplasma"], c: 0 },
  { q: "Quale metallo è liquido a temperatura ambiente?", o: ["Mercurio", "Piombo", "Ferro", "Rame"], c: 0 },
  { q: "Quale vitamina viene prodotta grazie all'esposizione al sole?", o: ["Vitamina D", "Vitamina C", "Vitamina A", "Vitamina B12"], c: 0 },
  { q: "Chi è riconosciuto dal Congresso USA (2002) come inventore del telefono?", o: ["Antonio Meucci", "Alexander Graham Bell", "Thomas Edison", "Guglielmo Marconi"], c: 0 },
  { q: "Quale italiano vinse il Nobel per l'invenzione della radio?", o: ["Guglielmo Marconi", "Nikola Tesla", "Thomas Edison", "Alexander Bell"], c: 0 },
  { q: "Quale pianeta è celebre per i suoi evidenti anelli?", o: ["Saturno", "Giove", "Urano", "Nettuno"], c: 0 },
  { q: "Qual è l'osso più lungo del corpo umano?", o: ["Femore", "Tibia", "Omero", "Radio"], c: 0 },
  { q: "Qual è il numero atomico dell'idrogeno?", o: ["1", "2", "0", "8"], c: 0 },
  { q: "Quale scienziato italiano fu processato per aver sostenuto l'eliocentrismo?", o: ["Galileo Galilei", "Giordano Bruno", "Niccolò Copernico", "Keplero"], c: 0 },
  { q: "Chi propose il modello eliocentrico (il Sole al centro)?", o: ["Niccolò Copernico", "Tolomeo", "Galileo Galilei", "Isaac Newton"], c: 0 },
  { q: "Qual è la formula chimica dell'anidride carbonica?", o: ["CO₂", "O₂", "CO", "C₂O"], c: 0 },
  { q: "Qual è l'animale più grande del mondo?", o: ["Balenottera azzurra", "Elefante africano", "Squalo balena", "Capodoglio"], c: 0 },
  { q: "Quante zampe ha un ragno?", o: ["Otto", "Sei", "Dieci", "Quattro"], c: 0 },
  { q: "Quale mammifero è capace di volare?", o: ["Pipistrello", "Scoiattolo volante", "Colibrì", "Rondine"], c: 0 },
  { q: "Qual è l'animale terrestre più veloce?", o: ["Ghepardo", "Leone", "Antilope", "Cavallo"], c: 0 },
  { q: "Qual è la temperatura di ebollizione dell'acqua a livello del mare?", o: ["100 °C", "90 °C", "120 °C", "80 °C"], c: 0 },
  { q: "Quale organo produce l'insulina?", o: ["Pancreas", "Fegato", "Reni", "Milza"], c: 0 },
  { q: "Quale scienziata vinse due premi Nobel (fisica e chimica)?", o: ["Marie Curie", "Lise Meitner", "Rosalind Franklin", "Ada Lovelace"], c: 0 },
  { q: "Qual è il satellite naturale della Terra?", o: ["La Luna", "Fobos", "Europa", "Titano"], c: 0 },
  { q: "Quale elemento chimico ha simbolo 'O'?", o: ["Ossigeno", "Oro", "Osmio", "Oganesson"], c: 0 },
  { q: "Quale gas è essenziale per la respirazione umana?", o: ["Ossigeno", "Azoto", "Anidride carbonica", "Elio"], c: 0 },
  { q: "Qual è l'osso più piccolo del corpo umano?", o: ["Staffa (orecchio)", "Falange", "Coccige", "Martello"], c: 0 },
  { q: "Quale parte del sangue trasporta l'ossigeno?", o: ["Globuli rossi", "Globuli bianchi", "Piastrine", "Plasma"], c: 0 },
  { q: "Quale scienziato scoprì la penicillina?", o: ["Alexander Fleming", "Louis Pasteur", "Robert Koch", "Edward Jenner"], c: 0 },

  // ---- Musica ----
  { q: "Chi compose 'Le quattro stagioni'?", o: ["Antonio Vivaldi", "Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Ludwig van Beethoven"], c: 0 },
  { q: "Chi compose la Nona Sinfonia con l''Inno alla gioia'?", o: ["Ludwig van Beethoven", "Mozart", "Bach", "Brahms"], c: 0 },
  { q: "Chi compose l'opera 'La Traviata'?", o: ["Giuseppe Verdi", "Giacomo Puccini", "Gioachino Rossini", "Vincenzo Bellini"], c: 0 },
  { q: "Chi compose 'Il barbiere di Siviglia'?", o: ["Gioachino Rossini", "Giuseppe Verdi", "Gaetano Donizetti", "Mozart"], c: 0 },
  { q: "Chi compose le opere 'La Bohème' e 'Tosca'?", o: ["Giacomo Puccini", "Giuseppe Verdi", "Pietro Mascagni", "Ruggero Leoncavallo"], c: 0 },
  { q: "Quale compositore è soprannominato il 'Cigno di Pesaro'?", o: ["Gioachino Rossini", "Giuseppe Verdi", "Giacomo Puccini", "Niccolò Paganini"], c: 0 },
  { q: "Di quale strumento fu celebre virtuoso Niccolò Paganini?", o: ["Violino", "Pianoforte", "Flauto", "Tromba"], c: 0 },
  { q: "Chi compose 'Il flauto magico' e 'Le nozze di Figaro'?", o: ["Mozart", "Beethoven", "Haydn", "Salieri"], c: 0 },
  { q: "Da quanti musicisti è composto un quartetto d'archi?", o: ["Quattro", "Tre", "Cinque", "Due"], c: 0 },
  { q: "Quante corde ha una chitarra classica standard?", o: ["Sei", "Quattro", "Cinque", "Sette"], c: 0 },
  { q: "Quale band britannica annoverava John Lennon e Paul McCartney?", o: ["The Beatles", "The Rolling Stones", "The Who", "Queen"], c: 0 },
  { q: "Chi era il cantante dei Queen?", o: ["Freddie Mercury", "Mick Jagger", "David Bowie", "Elton John"], c: 0 },
  { q: "Quale cantautore scrisse 'La canzone di Marinella'?", o: ["Fabrizio De André", "Lucio Battisti", "Lucio Dalla", "Francesco Guccini"], c: 0 },
  { q: "Chi cantava il brano 'Caruso'?", o: ["Lucio Dalla", "Fabrizio De André", "Lucio Battisti", "Claudio Baglioni"], c: 0 },
  { q: "Quante sono le note della scala musicale (do, re, mi...)?", o: ["Sette", "Cinque", "Otto", "Sei"], c: 0 },
  { q: "In quale città si tiene il celebre Festival della canzone italiana?", o: ["Sanremo", "Napoli", "Roma", "Bologna"], c: 0 },
  { q: "Chi compose il coro 'Va, pensiero' del Nabucco?", o: ["Giuseppe Verdi", "Gioachino Rossini", "Vincenzo Bellini", "Gaetano Donizetti"], c: 0 },
  { q: "Quale strumento ha tasti bianchi e neri?", o: ["Pianoforte", "Violino", "Tromba", "Arpa"], c: 0 },
  { q: "Chi è universalmente considerato il 'Re del Pop'?", o: ["Michael Jackson", "Elvis Presley", "Prince", "Stevie Wonder"], c: 0 },
  { q: "Chi è considerato il 'Re del Rock and Roll'?", o: ["Elvis Presley", "Chuck Berry", "Little Richard", "Buddy Holly"], c: 0 },
  { q: "Quale compositore tedesco divenne sordo ma continuò a comporre?", o: ["Beethoven", "Bach", "Wagner", "Schumann"], c: 0 },
  { q: "Quale strumento a fiato era suonato da Louis Armstrong?", o: ["Tromba", "Sassofono", "Clarinetto", "Trombone"], c: 0 },
  { q: "Chi cantò 'Nel blu dipinto di blu' (Volare)?", o: ["Domenico Modugno", "Claudio Villa", "Adriano Celentano", "Mina"], c: 0 },
  { q: "Quale gruppo rock pubblicò l'album 'The Dark Side of the Moon'?", o: ["Pink Floyd", "Led Zeppelin", "Deep Purple", "Genesis"], c: 0 },
  { q: "Chi compose il celebre 'Boléro'?", o: ["Maurice Ravel", "Claude Debussy", "Erik Satie", "Hector Berlioz"], c: 0 },

  // ---- Cinema e TV ----
  { q: "Chi diresse il film 'La dolce vita'?", o: ["Federico Fellini", "Luchino Visconti", "Michelangelo Antonioni", "Vittorio De Sica"], c: 0 },
  { q: "Quale film fece vincere l'Oscar a Roberto Benigni?", o: ["La vita è bella", "Mediterraneo", "Nuovo Cinema Paradiso", "Il postino"], c: 0 },
  { q: "Chi diresse 'Nuovo Cinema Paradiso'?", o: ["Giuseppe Tornatore", "Federico Fellini", "Paolo Sorrentino", "Gabriele Salvatores"], c: 0 },
  { q: "Quale regista vinse l'Oscar con 'La grande bellezza'?", o: ["Paolo Sorrentino", "Giuseppe Tornatore", "Matteo Garrone", "Nanni Moretti"], c: 0 },
  { q: "Chi interpreta Don Vito Corleone ne 'Il Padrino'?", o: ["Marlon Brando", "Al Pacino", "Robert De Niro", "James Caan"], c: 0 },
  { q: "Chi diresse 'Il Padrino'?", o: ["Francis Ford Coppola", "Martin Scorsese", "Steven Spielberg", "George Lucas"], c: 0 },
  { q: "Quale saga ha per protagonista un giovane mago di nome Harry?", o: ["Harry Potter", "Il Signore degli Anelli", "Le Cronache di Narnia", "Twilight"], c: 0 },
  { q: "Chi diresse 'Jurassic Park' ed 'E.T. l'extra-terrestre'?", o: ["Steven Spielberg", "George Lucas", "James Cameron", "Christopher Nolan"], c: 0 },
  { q: "In quale saga si dice 'Che la Forza sia con te'?", o: ["Guerre Stellari (Star Wars)", "Star Trek", "Matrix", "Blade Runner"], c: 0 },
  { q: "Chi interpreta Jack nel film 'Titanic'?", o: ["Leonardo DiCaprio", "Brad Pitt", "Tom Cruise", "Johnny Depp"], c: 0 },
  { q: "Chi diresse 'Titanic' e 'Avatar'?", o: ["James Cameron", "Steven Spielberg", "Christopher Nolan", "Ridley Scott"], c: 0 },
  { q: "Quale comico napoletano è soprannominato il 'principe della risata'?", o: ["Totò", "Eduardo De Filippo", "Massimo Troisi", "Peppino De Filippo"], c: 0 },
  { q: "Quale film d'animazione Disney ha per protagonista un leone?", o: ["Il Re Leone", "Bambi", "Dumbo", "Aladdin"], c: 0 },
  { q: "Quale serie TV è ambientata a Westeros, con il 'Trono di Spade'?", o: ["Game of Thrones", "Vikings", "The Witcher", "Lost"], c: 0 },
  { q: "Quale attore-regista interpretò l'ispettore Callaghan ed è regista di 'Gran Torino'?", o: ["Clint Eastwood", "Robert Redford", "Paul Newman", "Burt Lancaster"], c: 0 },
  { q: "In quale film del 1994 il protagonista 'Forrest' corre attraverso l'America?", o: ["Forrest Gump", "Rain Man", "Philadelphia", "Big"], c: 0 },
  { q: "Chi diresse 'Pulp Fiction'?", o: ["Quentin Tarantino", "Martin Scorsese", "Fratelli Coen", "David Fincher"], c: 0 },
  { q: "Quale attrice italiana premio Oscar è protagonista de 'La ciociara'?", o: ["Sophia Loren", "Gina Lollobrigida", "Claudia Cardinale", "Monica Vitti"], c: 0 },
  { q: "Qual è il primo film della trilogia de 'Il Signore degli Anelli'?", o: ["La Compagnia dell'Anello", "Le Due Torri", "Il Ritorno del Re", "Lo Hobbit"], c: 0 },
  { q: "Quale regista è noto per 'Inception' e 'Interstellar'?", o: ["Christopher Nolan", "Ridley Scott", "James Cameron", "Denis Villeneuve"], c: 0 },

  // ---- Sport ----
  { q: "Ogni quanti anni si tengono i Giochi Olimpici estivi?", o: ["Quattro anni", "Due anni", "Tre anni", "Cinque anni"], c: 0 },
  { q: "Quanti giocatori schiera in campo una squadra di calcio?", o: ["Undici", "Dieci", "Dodici", "Nove"], c: 0 },
  { q: "In che anno l'Italia vinse i Mondiali di calcio per la quarta volta?", o: ["2006", "1982", "1994", "2002"], c: 0 },
  { q: "Quante volte l'Italia ha vinto i Mondiali di calcio?", o: ["Quattro", "Tre", "Due", "Cinque"], c: 0 },
  { q: "In quale sport si usa una racchetta e una pallina gialla su un campo con rete?", o: ["Tennis", "Badminton", "Squash", "Ping pong"], c: 0 },
  { q: "Quanti giocatori per squadra sono in campo nella pallavolo?", o: ["Sei", "Cinque", "Sette", "Quattro"], c: 0 },
  { q: "Quanti giocatori per squadra sono in campo nel basket?", o: ["Cinque", "Sei", "Sette", "Quattro"], c: 0 },
  { q: "In quale città italiana si tennero le Olimpiadi estive del 1960?", o: ["Roma", "Torino", "Milano", "Napoli"], c: 0 },
  { q: "Quale città italiana ospitò le Olimpiadi invernali del 2006?", o: ["Torino", "Cortina d'Ampezzo", "Milano", "Sestriere"], c: 0 },
  { q: "Quale pilota di F1 ha vinto sette titoli mondiali, record condiviso con Hamilton?", o: ["Michael Schumacher", "Ayrton Senna", "Alain Prost", "Sebastian Vettel"], c: 0 },
  { q: "In quale disciplina eccelleva Valentino Rossi?", o: ["Motociclismo (MotoGP)", "Formula 1", "Ciclismo", "Sci"], c: 0 },
  { q: "Qual è la più importante corsa ciclistica a tappe italiana?", o: ["Giro d'Italia", "Tour de France", "Vuelta", "Milano-Sanremo"], c: 0 },
  { q: "In una finale Slam maschile di tennis, chi vince conquista...", o: ["Tre set su cinque", "Due set su tre", "Quattro set", "Un solo set"], c: 0 },
  { q: "In quale sport si segna un 'touchdown'?", o: ["Football americano", "Rugby", "Calcio", "Baseball"], c: 0 },
  { q: "Quale nuotatore italiano è campione olimpico nei 1500 m stile libero?", o: ["Gregorio Paltrinieri", "Filippo Magnini", "Massimiliano Rosolino", "Domenico Fioravanti"], c: 0 },
  { q: "Quante buche ha un percorso di golf regolamentare?", o: ["Diciotto", "Nove", "Dodici", "Ventiquattro"], c: 0 },
  { q: "In quale disciplina gareggiava il campione Alberto Tomba?", o: ["Sci alpino", "Sci di fondo", "Snowboard", "Pattinaggio"], c: 0 },
  { q: "Quali due squadre di calcio giocano allo stadio di San Siro?", o: ["Milan e Inter", "Juventus e Torino", "Roma e Lazio", "Genoa e Sampdoria"], c: 0 },
  { q: "Quanti minuti dura un tempo regolamentare nel calcio?", o: ["45", "30", "40", "60"], c: 0 },
  { q: "Quale tennista detiene il record di titoli del Grande Slam maschile (24)?", o: ["Novak Djokovic", "Roger Federer", "Rafael Nadal", "Pete Sampras"], c: 0 },

  // ---- Mitologia e religione ----
  { q: "Chi era il re degli dèi nella mitologia greca?", o: ["Zeus", "Poseidone", "Ade", "Apollo"], c: 0 },
  { q: "Chi era il dio del mare nella mitologia greca?", o: ["Poseidone", "Zeus", "Ares", "Ermes"], c: 0 },
  { q: "Come si chiama Zeus nella mitologia romana?", o: ["Giove", "Marte", "Nettuno", "Apollo"], c: 0 },
  { q: "Chi era la dea greca dell'amore e della bellezza?", o: ["Afrodite", "Atena", "Era", "Artemide"], c: 0 },
  { q: "Chi uccise il Minotauro nel labirinto?", o: ["Teseo", "Eracle", "Perseo", "Giasone"], c: 0 },
  { q: "Quale eroe greco aveva un punto vulnerabile nel tallone?", o: ["Achille", "Ettore", "Ulisse", "Aiace"], c: 0 },
  { q: "A chi la tradizione attribuisce l'Iliade e l'Odissea?", o: ["Omero", "Esiodo", "Virgilio", "Sofocle"], c: 0 },
  { q: "Quale eroe viaggiò dieci anni per tornare a Itaca?", o: ["Ulisse (Odisseo)", "Achille", "Enea", "Ettore"], c: 0 },
  { q: "Quante fatiche dovette compiere Eracle (Ercole)?", o: ["Dodici", "Dieci", "Sette", "Nove"], c: 0 },
  { q: "Chi era il dio romano della guerra?", o: ["Marte", "Giove", "Mercurio", "Vulcano"], c: 0 },
  { q: "Quanti sono i comandamenti nella tradizione cristiana?", o: ["Dieci", "Sette", "Dodici", "Cinque"], c: 0 },
  { q: "In quale città nacque Gesù secondo i Vangeli?", o: ["Betlemme", "Nazareth", "Gerusalemme", "Cafarnao"], c: 0 },
  { q: "Qual è il libro sacro dell'Islam?", o: ["Corano", "Bibbia", "Torah", "Veda"], c: 0 },
  { q: "Quanti furono gli apostoli di Gesù?", o: ["Dodici", "Dieci", "Sette", "Quattordici"], c: 0 },
  { q: "Chi, secondo la Bibbia, guidò gli Ebrei fuori dall'Egitto?", o: ["Mosè", "Abramo", "Davide", "Noè"], c: 0 },

  // ---- Cucina e tradizioni ----
  { q: "Di quale città è originaria la pizza margherita?", o: ["Napoli", "Roma", "Palermo", "Firenze"], c: 0 },
  { q: "Quale formaggio, oltre al guanciale, è tipico della carbonara?", o: ["Pecorino romano", "Mozzarella", "Gorgonzola", "Fontina"], c: 0 },
  { q: "Da quale regione è originario il pesto?", o: ["Liguria", "Piemonte", "Lombardia", "Toscana"], c: 0 },
  { q: "Quale città è la patria del ragù alla bolognese?", o: ["Bologna", "Modena", "Parma", "Ferrara"], c: 0 },
  { q: "Di quale regione è tipico il vino Chianti?", o: ["Toscana", "Piemonte", "Veneto", "Puglia"], c: 0 },
  { q: "Di quale regione è tipico il vino Barolo?", o: ["Piemonte", "Toscana", "Sicilia", "Friuli"], c: 0 },
  { q: "Qual è l'ingrediente base del risotto?", o: ["Riso", "Pasta", "Patate", "Mais"], c: 0 },
  { q: "Quale dolce è fatto con savoiardi, caffè e mascarpone?", o: ["Tiramisù", "Cannolo", "Panna cotta", "Zuppa inglese"], c: 0 },
  { q: "Di quale città è tipico il panettone?", o: ["Milano", "Verona", "Torino", "Genova"], c: 0 },
  { q: "Di quale regione è tipica la mozzarella di bufala?", o: ["Campania", "Puglia", "Lazio", "Calabria"], c: 0 },
  { q: "Di quale regione è il prosciutto di Parma?", o: ["Emilia-Romagna", "Toscana", "Veneto", "Lombardia"], c: 0 },
  { q: "Quale pasta ripiena ha la forma di un piccolo 'ombelico'?", o: ["Tortellini", "Penne", "Fusilli", "Rigatoni"], c: 0 },
  { q: "In quale regione si produce principalmente il Parmigiano Reggiano?", o: ["Emilia-Romagna", "Lombardia", "Piemonte", "Veneto"], c: 0 },
  { q: "Quale liquore italiano si ottiene dalla buccia dei limoni?", o: ["Limoncello", "Grappa", "Amaretto", "Sambuca"], c: 0 },
  { q: "Quale dolce siciliano è ripieno di ricotta dolce?", o: ["Cannolo", "Tiramisù", "Babà", "Panettone"], c: 0 },

  // ---- Lingua italiana e modi di dire ----
  { q: "Quante lettere ha l'alfabeto italiano tradizionale (senza le straniere)?", o: ["21", "26", "24", "22"], c: 0 },
  { q: "Quale di queste parole è scritta correttamente?", o: ["Coscienza", "Cosciensa", "Conoscienza", "Scenziato"], c: 0 },
  { q: "Qual è il plurale di 'uomo'?", o: ["Uomini", "Uomi", "Uomeni", "Uomo"], c: 0 },
  { q: "Cosa significa l'augurio 'in bocca al lupo'?", o: ["Buona fortuna", "Avvertimento di pericolo", "Un insulto", "Un saluto formale"], c: 0 },
  { q: "Cosa significa l'espressione 'acqua in bocca'?", o: ["Mantenere un segreto", "Avere molta sete", "Parlare troppo", "Essere timidi"], c: 0 },
  { q: "Quale di queste è un sinonimo di 'veloce'?", o: ["Rapido", "Lento", "Pigro", "Stanco"], c: 0 },
  { q: "Qual è il contrario di 'generoso'?", o: ["Avaro", "Gentile", "Ricco", "Allegro"], c: 0 },
  { q: "Quale articolo si usa con la parola 'zaino'?", o: ["Lo", "Il", "La", "Gli"], c: 0 },
  { q: "Cosa significa 'prendere due piccioni con una fava'?", o: ["Ottenere due risultati con un'azione", "Sprecare tempo", "Fare un grande pasto", "Fallire un compito"], c: 0 },
  { q: "Quale accademia è il principale riferimento per la lingua italiana?", o: ["Accademia della Crusca", "Accademia dei Lincei", "Accademia d'Italia", "Società Dante Alighieri"], c: 0 },
  { q: "Qual è il superlativo assoluto dell'aggettivo 'buono'?", o: ["Ottimo", "Migliore", "Più buono", "Benissimo"], c: 0 },
  { q: "Cosa significa l'espressione 'tagliare la corda'?", o: ["Scappare via", "Litigare", "Lavorare sodo", "Addormentarsi"], c: 0 },
  { q: "Quale di queste parole è un verbo?", o: ["Correre", "Veloce", "Bello", "Tavolo"], c: 0 },
  { q: "Qual è il femminile di 'attore'?", o: ["Attrice", "Attora", "Attoressa", "Attori"], c: 0 },
  { q: "Cosa significa 'avere le mani bucate'?", o: ["Spendere troppo denaro", "Essere molto abili", "Essere feriti", "Lavorare male"], c: 0 },

  // ---- Politica, istituzioni e varie ----
  { q: "Chi è il capo dello Stato in Italia?", o: ["Il Presidente della Repubblica", "Il Presidente del Consiglio", "Il Papa", "Il Re"], c: 0 },
  { q: "Dove ha sede il Presidente della Repubblica Italiana?", o: ["Quirinale", "Palazzo Chigi", "Montecitorio", "Palazzo Madama"], c: 0 },
  { q: "Da quante camere è composto il Parlamento italiano?", o: ["Due (Camera e Senato)", "Una", "Tre", "Quattro"], c: 0 },
  { q: "Quanti anni dura il mandato del Presidente della Repubblica italiana?", o: ["Sette", "Cinque", "Quattro", "Sei"], c: 0 },
  { q: "Qual è la valuta usata in Italia dal 2002?", o: ["Euro", "Lira", "Franco", "Dollaro"], c: 0 },
  { q: "In quale città ha sede la Commissione Europea?", o: ["Bruxelles", "Strasburgo", "Lussemburgo", "Ginevra"], c: 0 },
  { q: "Quanti colori ha la bandiera italiana?", o: ["Tre", "Due", "Quattro", "Cinque"], c: 0 },
  { q: "Quali sono i colori della bandiera italiana?", o: ["Verde, bianco e rosso", "Rosso, bianco e blu", "Giallo e rosso", "Verde, bianco e blu"], c: 0 },
  { q: "In quale città ha sede principale l'ONU (il 'Palazzo di Vetro')?", o: ["New York", "Ginevra", "Parigi", "Vienna"], c: 0 },
  { q: "Qual è l'inno nazionale italiano?", o: ["Il Canto degli Italiani (Inno di Mameli)", "Va, pensiero", "Nessun dorma", "O sole mio"], c: 0 },
];
